### ISSUE TITLE
Unhandled Promise rejection: no value for 'isPlaying' in function 'updateIsPlaying()'

### ISSUE THREAD

**Issue by NorthFred** [ingageco/capacitor-music-controls-plugin-v3#3]
The function `updateIsPlaying` only accepts a boolean value by the IDE.

```
(method) CapacitorMusicControlsPlugin.updateIsPlaying(isPlaying: boolean): void
```

When however running the plugin on Android, following error is printed to the console:

```
VM3:217 result CapacitorMusicControls.updateIsPlaying (#66556477)
polyfills.js:1 Unhandled Promise rejection: error updateIsPlaying: org.json.JSONException: No value for isPlaying ; Zone: <root> ; Task: Promise.then ; Value: Error: error updateIsPlaying: org.json.JSONException: No value for isPlaying
    at returnResult (VM3:756:32)
    at win.androidBridge.onmessage (VM3:731:21) Error: error updateIsPlaying: org.json.JSONException: No value for isPlaying
    at returnResult (http://localhost/:756:32)
    at win.androidBridge.onmessage (http://localhost/:731:21)
```

Note that the instructions specify following:

```
CapacitorMusicControls.updateIsPlaying({
    isPlaying: true, // affects Android only
    elapsed: timeElapsed // affects iOS Only
}).then(()=>{
	// SUCCESS
})
.catch(e=>{
	console.log(e);
});
```

But providing the object in the example is not supported, a boolean must be specified to the function.

**Comment by ingageco** [comment]
When you really look at this, both in documentation and code, it doesn't make sense. updateElapsed just calls updateIsPlaying on iOS, but doesn't update anything from what i can tell. On android, it just toggles isPlaying. Im sure this was something brought over from the original cordova plugin, but we can improve

**Comment by ingageco** [comment]
Definition updated in v1.0.12 to require an object as specified in the docs. Still questionable as to whether it actually does anything on iOS.

**Comment by NorthFred** [comment]
@ingageco I'll verify this on Android by next week.

**Comment by NorthFred** [comment]
@ingageco Verified in v.1.0.12 on Android 12+.
