### ISSUE TITLE
(Android) Recreating the Music Controls also appears to create a new instance of the listener?

### ISSUE THREAD

**Issue by NorthFred** [ingageco/capacitor-music-controls-plugin-v3#4]
I was previously using the Cordova implementation of the Music Controller for streaming audio from a live stream.

Following use case was handled correctly by the Cordova plugin:

0) Pressing PLAY or PAUSE button in the Controller is calling a single function which will handle the stream state, let's call this function `handleStream()`.

1) Before the audio stream is playing, the Music Controls listener is added: `CapacitorMusicControls.addListener('controlsNotification',....)`
2) Start playing an audio stream --> Music Controls are created and PAUSE icon is shown, `handleStream()` starts playing the music.
2) Press the PAUSE icon in the controller --> stream is stopped ('isPlaying' is set to false), `handleStream()` pauses the music.
3) Press the PLAY icon in the controller --> Music Controls are re-created (the existing listener persists and is not added again), `handleStream()` plays the music.
4) Press the PAUSE icon in the controller --> stream is stopped ('isPlaying' is set to false), `handleStream()`  pauses the music.
5) Press the PLAY icon in the controller --> Music Controls are re-created and `handleStream()`  plays the music.

Re-creating the Music Controls is a necessity, because it also enables the Music Controller to show the metadata linked to the currently playing song. Meaning, also when the song in the audio stream changes, the Music Controls are recreated to show the new Title + Artist + Album art.

This Capacitor plugin works differently - following behavior is observed on ANDROID:

1) Listener is added for the Music Control actions
2) Start playing an audio stream --> Music Controls are created and PAUSE icon is shown
3) Press the PAUSE  icon in the controller --> `music-controls-pause` message is received by the controller and `handleStream()` stops the audio stream.
4) Press the PLAY icon in the controller --> `music-controls-play` message is received by the controller and `handleStream()` plays the music again.
5) Press the PAUSE icon in the controller --> `music-controls-pause` **is received TWICE by the controller** --> **`handleStream()` is called TWICE and the music will instantly PAUSE and PLAY AGAIN.**
6) All subsequent presses of the PAUSE icon will duplicate the `music-controls-pause` action messages and `handleStream()` will be called multiple times, thus pausing + playing the stream quickly several times in a row.

Without looking at the plugin code, it seems that recreating the Music Controls with the 'create()' function will also add an additional listener to the controller?

**Comment by ingageco** [comment]
@NorthFred As i understand it, this boils down to one simple thing - re-creating the controls spawns a new listener without removing the old one, thus multiplying events. Correct?

**Comment by NorthFred** [comment]
@ingageco Spot-on, that's what seems to be happening.

**Comment by ingageco** [comment]
Ok try 1.0.13 and see if that solves it + causes any additional problems. 

This is getting pretty deep into Java and im not 100% certain which of the components of the Java code handle this. So i am using a bit of the destroy code in the initializer, since it could be called twice, to avoid creating what i think is the listener twice.

**Comment by NorthFred** [comment]
@ingageco Initial testing shows that this is now fixed. I will be doing more extensive testing during the coming days to verify that the plugin is now stable on Android.

Many thanks for your quick response and fixes!!
