### ISSUE TITLE
Media controls not shown on Android API level 33+

### ISSUE THREAD

**Issue by NorthFred** [ingageco/capacitor-music-controls-plugin-v3#7]
When targeting and compiling the app with Android SDK version 33 (Android 13), the Media Controls are **no longer shown** for the app.  The emulator does not show error messages related to this.

In contrast, when targeting the app to SDK 32, but compiling with SDK version 33, a confirmation dialog is shown "_Allow xAPPx to send you notifications?_" (see screenshot) when the app wants to show the Media Controls.  When allowing this, the Media Controls are shown. (Note that there is also a "Notifications" setting under App info, where these can be switched on or off).

![kuva](https://user-images.githubusercontent.com/26854315/226845473-1eb82e41-78cc-421b-897b-1b33e19985f5.png)

![kuva](https://user-images.githubusercontent.com/26854315/226845293-23b1f768-f40a-4611-b51e-f3cf18d63fdb.png)

When targeting and compiling with Android SDK 33, there is no such option to enable the Notifications. They are disabled by default, hence resulting in the Media Controls not being shown on Android 14.

![kuva](https://user-images.githubusercontent.com/26854315/226848476-6a3992e7-a0f5-4ce6-964e-94fd30a20091.png)

Note that by end of August 2023, new apps and app updates will require to **target SDK API level 33.**

**Comment by ingageco** [comment]
@NorthFred I've got to go through the Capacitor docs and see what they say about these new permissions.

**Comment by ingageco** [comment]
@NorthFred Just browsing the cordova version and reading some of the Android 13 docs, it seems that media playback is no longer considered a notification. therefore, registering it in the old method requires notification permissions, but registering it in the new way does not. 

i am a little confused on how this can be backwards compatible, and im hoping this doesn't mean i have to do a lot of check "if < api level 33", etc. normally i wouldn't complain, but remember, i'm not a java developer.

**Comment by ingageco** [comment]
@NorthFred please test the android-13-style branch and let me know what is working/isnt. it catches most of the differences up that exist between this and the cordova version.

**Comment by NorthFred** [comment]
@ingageco Great! I'll have a look this evening!

**Comment by NorthFred** [comment]
@ingageco I'll close this one, since it's being handled in this issue: https://github.com/ingageco/capacitor-music-controls-plugin-v3/issues/11
